# Generated by Django 4.2.1 on 2023-06-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=28, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=10, verbose_name='RG')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=11, verbose_name='Celular')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id_locacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_contratacao', models.CharField(max_length=10, verbose_name='Data da contratacao')),
                ('data_locacao', models.CharField(max_length=10, verbose_name='Data da locacao')),
                ('nome_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id_recebimento', models.AutoField(primary_key=True, serialize=False)),
                ('data_recebimento', models.DateField()),
                ('valor_recebimento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_locacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.locacao')),
                ('nome_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.cliente')),
            ],
        ),
    ]
