# Generated by Django 4.2.1 on 2023-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=28, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=10, verbose_name='RG')),
                ('birth_date', models.DateField()),
                ('telefone', models.CharField(max_length=11, verbose_name='Celular')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
            ],
        ),
    ]
